routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{
    HomeController, 
    AdminController, 
    CategoryController, 
    PostController,
    SettingController
};


Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/detail/{slug}/{id}', [HomeController::class, 'detail'])->name('detail');
Route::get('/all-categories', [HomeController::class, 'all_category'])->name('all-category');
Route::get('/category/{slug}/{id}', [HomeController::class, 'category'])->name('category');
Route::post('/save-comment/{slug}/{id}', [HomeController::class, 'save_comment'])->name('save-comment');
Route::get('/save-post-form', [HomeController::class, 'save_post_form'])->name('save-post');
Route::post('/save-post-form', [HomeController::class, 'save_post_data'])->name('save-post-data');
Route::get('/manage-posts', [HomeController::class, 'manage_posts'])->name('manage-posts');

// Admin
Route::get('/admin/login', [AdminController::class, 'login'])->name('login');
Route::post('/admin/login', [AdminController::class, 'submit_login']);
Route::get('/admin/logout', [AdminController::class, 'logout'])->name('logout');
Route::get('/admin/dashboard', [AdminController::class, 'dashboard'])->name('admin.dashboard');

// Comments
Route::get('/admin/comment', [AdminController::class, 'comments'])->name('comments');
Route::get('/admin/comment/delete/{id}', [AdminController::class, 'delete_comment'])->name('delete-comment');

// Users
Route::get('/admin/user', [AdminController::class, 'users'])->name('users');
Route::get('/admin/user/delete/{id}', [AdminController::class, 'delete_user'])->name('delete-user');

// Categories
Route::get('admin/category/{id}/delete',[CategoryController::class,'destroy']);
Route::resource('/admin/category', CategoryController::class);

// Posts
Route::get('admin/post/{id}/delete',[PostController::class,'destroy']);
Route::resource('/admin/post', PostController::class);

// Settings
Route::get('/admin/setting', [SettingController::class, 'index'])->name('setting');
Route::post('/admin/setting', [SettingController::class, 'save_settings'])->name('save_setting');

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/', function () {
//     return view('welcome');
// });

resources/views/includes/admin/footer.blade.php
<footer class="sticky-footer">
    <div class="container my-auto">
    <div class="copyright text-center my-auto">
        <span>Copyright © Your Website 2018</span>
    </div>
    </div>
</footer>

resources/views/includes/admin/meta.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title>@yield('title')</title>

resources/views/includes/admin/navbar.blade.php
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="index.html">Laravel Blog</a>
    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars"></i>
    </button>
</nav>

resources/views/includes/admin/script.blade.php
<!-- Bootstrap core JavaScript-->
<script src="{{asset('backend')}}/vendor/jquery/jquery.min.js"></script>
<script src="{{asset('backend')}}/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="{{asset('backend')}}/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="{{asset('backend')}}/vendor/datatables/jquery.dataTables.js"></script>
<script src="{{asset('backend')}}/vendor/datatables/dataTables.bootstrap4.js"></script>

<!-- Custom scripts for all pages-->
<script src="{{asset('backend')}}/js/sb-admin.min.js"></script>

<!-- Dashboard -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="{{ asset('backend/js/scripts.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="{{ asset('backend/assets/demo/chart-area-demo.js') }}"></script>
<script src="{{ asset('backend/assets/demo/chart-bar-demo.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="{{ asset('backend/js/datatables-simple-demo.js') }}"></script>

resources/views/includes/admin/sidebar.blade.php
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="{{ route('admin.dashboard') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span>
        </a>
    </li>
    <!-- Category -->
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-fw fa-list"></i>
        <span>Category</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
        <a class="dropdown-item" href="{{ route('category.index') }}">View All</a>
        <a class="dropdown-item" href="{{ route('category.create') }}">Add New</a>
        </div>
    </li>
    <!-- Post -->
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-fw fa-address-card"></i>
        <span>Post</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
        <a class="dropdown-item" href="{{ route('post.index') }}">View All</a>
        <a class="dropdown-item" href="{{ route('post.create') }}">Add New</a>
        </div>
    </li>
    <!-- Comments -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('comments') }}">
        <i class="fas fa-fw fa-comments"></i>
        <span>Comments</span>
        </a>
    </li>
    <!-- Users -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('users') }}">
        <i class="fas fa-fw fa-users"></i>
        <span>Users</span>
        </a>
    </li>
     <!-- Settings -->
     <li class="nav-item">
        <a class="nav-link" href="{{ route('setting') }}">
        <i class="fas fa-fw fa-comments"></i>
        <span>Settings</span>
        </a>
    </li>
    <!-- Logout -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('logout') }}">
        <i class="fas fa-fw fa-sign-out-alt"></i>
        <span>Logout</span>
        </a>
    </li>
</ul>

resources/views/includes/admin/style.blade.php
<!-- Bootstrap core CSS-->
<link href="{{asset('backend')}}/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom fonts for this template-->
<link href="{{asset('backend')}}/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Page level plugin CSS-->
<link href="{{asset('backend')}}/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{asset('backend')}}/css/sb-admin.css" rel="stylesheet">

<!-- Dashboard -->
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
<link href="{{ asset('backend/css/styles.css') }}" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>